# Generated by Django 5.1.2 on 2024-11-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_appointment_status_advice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
