# Generated by Django 5.1.2 on 2024-11-23 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_doctormodel_bio_doctormodel_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='insurance',
            field=models.CharField(choices=[('rama', 'RAMA'), ('mmi', 'MMI'), ('mituelle', 'Mituelle'), ('none', 'None')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='symptoms',
            field=models.CharField(choices=[('eyes', 'Eye pain or discomfort'), ('headache', 'Persistent or severe headaches'), ('injury', 'Joint or muscle pain')], default='Not Known', max_length=100),
        ),
    ]
