# Generated by Django 5.1.2 on 2024-11-24 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_customuser_is_doctor_customuser_is_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_patient',
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='specialization',
            field=models.CharField(choices=[('eyes', 'Eyes Specialist'), ('headache', 'Headache Specialist'), ('injury', 'Injury Specialist')], default='Nurse', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='user',
            field=models.OneToOneField(default='guest', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
