# Generated by Django 5.1.2 on 2024-11-24 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_customuser_is_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
