# Generated by Django 5.1.2 on 2024-11-25 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_doctormodel_user_alter_patientmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_patient',
        ),
    ]
